### ISSUE TITLE
NEW Issue: raise IOError("Cannot understand given URI: %s." % uri_r) OSError: Cannot understand given URI: None.

### ISSUE THREAD

**Issue by johnnyvng** [alexlaverty/python-reddit-youtube-bot#90]
Hi all,

Just recently I got this error on both ubuntu VMs, not sure if you are getting error as well

raise IOError("Cannot understand given URI: %s." % uri_r) 
OSError: Cannot understand given URI: None.

**Comment by johnnyvng** [comment]
NVM, must be something wrong with reddit server....it's up and running fine today

**Comment by alexlaverty** [comment]
Was an issue with the Lexica api endpoint it was returning a 500 error, this is how the thumbnail images are scraped. 

for example :
https://lexica.art/api/v1/search?q=apple
